/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ht2yXpMfc3o
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardHeader, CardContent, CardTitle, CardDescription } from "@/components/ui/card"

export function Component() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Acme Dairy Farm</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Products
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
            <img
              src="/placeholder.svg"
              width="550"
              height="550"
              alt="Farm"
              className="mx-auto aspect-square overflow-hidden rounded-xl object-cover sm:w-full lg:order-last"
            />
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                  Welcome to Acme Dairy Farm
                </h1>
                <p className="max-w-[600px] text-muted-foreground md:text-xl">
                  Nestled in the heart of the countryside, Acme Dairy Farm has been providing high-quality dairy
                  products to our community for over 50 years. Our family-owned farm is committed to sustainable and
                  ethical farming practices, ensuring that every product we offer is fresh, nutritious, and delicious.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Our Dairy Products</h2>
                <p className="max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Explore our selection of fresh, high-quality dairy products made from the milk of our happy, grass-fed
                  cows.
                </p>
              </div>
            </div>
            <div className="mx-auto grid grid-cols-1 gap-6 py-12 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-2">
              <div className="space-y-4">
                <h3 className="text-2xl font-bold">Latticini</h3>
                <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-2">
                  <Card className="flex flex-col items-center justify-between">
                    <CardHeader>
                      <img
                        src="/placeholder.svg"
                        width="200"
                        height="200"
                        alt="Milk"
                        className="aspect-square overflow-hidden rounded-xl object-cover"
                      />
                    </CardHeader>
                    <CardContent className="text-center">
                      <CardTitle>Whole Milk</CardTitle>
                      <CardDescription>
                        Our creamy, full-fat milk is perfect for drinking, baking, and more.
                      </CardDescription>
                      <div className="font-bold text-lg">$3.99</div>
                    </CardContent>
                  </Card>
                  <Card className="flex flex-col items-center justify-between">
                    <CardHeader>
                      <img
                        src="/placeholder.svg"
                        width="200"
                        height="200"
                        alt="Cheese"
                        className="aspect-square overflow-hidden rounded-xl object-cover"
                      />
                    </CardHeader>
                    <CardContent className="text-center">
                      <CardTitle>Artisanal Cheese</CardTitle>
                      <CardDescription>
                        Our handcrafted cheeses are made with care and attention to detail.
                      </CardDescription>
                      <div className="font-bold text-lg">$7.99</div>
                    </CardContent>
                  </Card>
                  <Card className="flex flex-col items-center justify-between">
                    <CardHeader>
                      <img
                        src="/placeholder.svg"
                        width="200"
                        height="200"
                        alt="Yogurt"
                        className="aspect-square overflow-hidden rounded-xl object-cover"
                      />
                    </CardHeader>
                    <CardContent className="text-center">
                      <CardTitle>Creamy Yogurt</CardTitle>
                      <CardDescription>
                        Our thick, rich yogurt is perfect for a healthy snack or breakfast.
                      </CardDescription>
                      <div className="font-bold text-lg">$2.99</div>
                    </CardContent>
                  </Card>
                  <Card className="flex flex-col items-center justify-between">
                    <CardHeader>
                      <img
                        src="/placeholder.svg"
                        width="200"
                        height="200"
                        alt="Butter"
                        className="aspect-square overflow-hidden rounded-xl object-cover"
                      />
                    </CardHeader>
                    <CardContent className="text-center">
                      <CardTitle>Artisanal Butter</CardTitle>
                      <CardDescription>
                        Our small-batch butter is perfect for baking, cooking, and spreading.
                      </CardDescription>
                      <div className="font-bold text-lg">$5.99</div>
                    </CardContent>
                  </Card>
                </div>
              </div>
              <div className="space-y-4">
                <h3 className="text-2xl font-bold">Marmellate</h3>
                <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-2">
                  <Card className="flex flex-col items-center justify-between">
                    <CardHeader>
                      <img
                        src="/placeholder.svg"
                        width="200"
                        height="200"
                        alt="Strawberry Jam"
                        className="aspect-square overflow-hidden rounded-xl object-cover"
                      />
                    </CardHeader>
                    <CardContent className="text-center">
                      <CardTitle>Strawberry Jam</CardTitle>
                      <CardDescription>
                        Our homemade strawberry jam is perfect for toast, scones, and more.
                      </CardDescription>
                      <div className="font-bold text-lg">$6.99</div>
                    </CardContent>
                  </Card>
                  <Card className="flex flex-col items-center justify-between">
                    <CardHeader>
                      <img
                        src="/placeholder.svg"
                        width="200"
                        height="200"
                        alt="Blueberry Jam"
                        className="aspect-square overflow-hidden rounded-xl object-cover"
                      />
                    </CardHeader>
                    <CardContent className="text-center">
                      <CardTitle>Blueberry Jam</CardTitle>
                      <CardDescription>
                        Our delicious blueberry jam is perfect for adding a touch of sweetness to your day.
                      </CardDescription>
                      <div className="font-bold text-lg">$6.99</div>
                    </CardContent>
                  </Card>
                  <Card className="flex flex-col items-center justify-between">
                    <CardHeader>
                      <img
                        src="/placeholder.svg"
                        width="200"
                        height="200"
                        alt="Raspberry Jam"
                        className="aspect-square overflow-hidden rounded-xl object-cover"
                      />
                    </CardHeader>
                    <CardContent className="text-center">
                      <CardTitle>Raspberry Jam</CardTitle>
                      <CardDescription>
                        Our tart and tangy raspberry jam is perfect for adding a burst of flavor to your meals.
                      </CardDescription>
                      <div className="font-bold text-lg">$6.99</div>
                    </CardContent>
                  </Card>
                  <Card className="flex flex-col items-center justify-between">
                    <CardHeader>
                      <img
                        src="/placeholder.svg"
                        width="200"
                        height="200"
                        alt="Apricot Jam"
                        className="aspect-square overflow-hidden rounded-xl object-cover"
                      />
                    </CardHeader>
                    <CardContent className="text-center">
                      <CardTitle>Apricot Jam</CardTitle>
                      <CardDescription>
                        Our sweet and tangy apricot jam is perfect for adding a touch of sunshine to your day.
                      </CardDescription>
                      <div className="font-bold text-lg">$6.99</div>
                    </CardContent>
                  </Card>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Acme Dairy Farm. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function MountainIcon({ props }: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
